package og.ogstartracker.utils

import kotlinx.coroutines.flow.Flow

/**
 * Returns a [Flow] whose values are generated by [transform] function that process the most
 * recently emitted values by each flow.
 *
 * Taken from: https://github.com/android/nowinandroid/blob/21777aba65c023a2ae0c83d2ddc19a7d69131acd/core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/SyncUtilities.kt#L23.
 */
fun <T1, T2, T3, T4, T5, T6, R> combine(
	flow: Flow<T1>,
	flow2: Flow<T2>,
	flow3: Flow<T3>,
	flow4: Flow<T4>,
	flow5: Flow<T5>,
	flow6: Flow<T6>,
	transform: suspend (T1, T2, T3, T4, T5, T6) -> R,
): Flow<R> = kotlinx.coroutines.flow.combine(
	kotlinx.coroutines.flow.combine(flow, flow2, flow3, ::Triple),
	kotlinx.coroutines.flow.combine(flow4, flow5, flow6, ::Triple),
) { t1, t2 ->
	transform(
		t1.first,
		t1.second,
		t1.third,
		t2.first,
		t2.second,
		t2.third,
	)
}
